class InqPerformanceApi {
  getInqPerformances() {
    const inqPerformances = [
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'WIN',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '',
          type3: '',
          type4: ''
        },
        specialcontainer: '1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      },
      {
        id: '5ece2c077e39da27658aa8a9',
        result: 'LOSS',
        inqNo: '2100088',
        revenue: '500',
        gp: '100',
        ros: '20',
        customer: 'JET INDUS',
        sale: 'JEERANAT',
        team: 'BD',
        mode: 'AE',
        term: 'DAP',
        pol: 'AMS',
        pod: 'BANGKOK',
        dest: '',
        commodity: 'AEROSPACE',
        volumeperweak: {
          type: 'DC',
          type1: '2',
          type2: '3',
          type3: '4',
          type4: '5'
        },
        specialcontainer: 'special1'
      }
    ];

    return Promise.resolve(inqPerformances);
  }
}

export const inqPerformanceApi = new InqPerformanceApi();
