export class Inquiry {
    inq_uuid: string
    inq_no: string
    inq_pol_id: string
    inq_pod_id: string
    inq_cus_id: string
    inq_user_id: string
    inq_agent_id: string
    inq_cr_id: string
    inq_timestamp: string
    inq_date: string
    inq_cus_type: string
    inq_mode: string
    inq_factory_location: string
    inq_incoterms: string
    inq_place_of_receipt: string
    inq_final_destination: string
    inq_type: string
    inq_cargo_readiness: string
    inq_qw_per_cntr: number
    inq_idea_rate_per_unit: number
    inq_container_20: number
    inq_container_40: number
    inq_container_40hc: number
    inq_container_cbm: number
    inq_commodity: string
    inq_special_container: string
    inq_freetime: string
    inq_other: string
    inq_agent_quote_comment: string
    inq_res_quote_status: string
    inq_res_actual_week_no: number
    inq_res_comment: string
    inq_res_reason: string
    inq_res_describe: string
    inq_res_ct_id_win: string
    inq_res_ct_price: number
    inq_res_loss_comment: string
    inq_status: string
    inq_quate_no: string
    inq_quate_date: string
    inq_rate_id: string
    inq_revenue: number
    inq_gp: number
    inq_quate_other: string
    inq_quate_sq_other: string
    inq_quate_comment: string
    inq_quate_freight_sq: string
    inq_disable: number
    inq_qtn: string
    inq_tx_time: string
    inq_day: number
    over_leadtime: boolean
    inq_ct_id: string
    inq_pickup_location: string
    inq_waiting_sales: number
    inq_waiting_mktg: number
    inq_waiting_cus: number
    inq_waiting_quotation: number
}
